# Generated by Django 2.2.11 on 2020-08-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200822_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf_of_cnpj',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf_or_cnpj',
            field=models.CharField(max_length=14, null=True, verbose_name='cpf_or_cnpj'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('company', 'a'), ('person', 'person')], max_length=124, verbose_name='account_type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='last name'),
        ),
    ]
