# Generated by Django 2.2.11 on 2020-08-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200823_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='accounts.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('remove', 'remove')], max_length=124, null=True, verbose_name='transaction_type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('company', 'company'), ('person', 'person')], max_length=124, verbose_name='account_type'),
        ),
    ]
