# Generated by Django 2.2.11 on 2020-08-25 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_transaction_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Campaign', verbose_name='campaign'),
        ),
    ]
